site_name: Configuration Profiles
repo_url: https://github.com/systopia/config-profiles
site_description: 'A guide for the Configuration Profiles CiviCRM extension.'
site_author: 'SYSTOPIA'
theme:
  name:
    material

nav:
  - Home: index.md
  - Implementing Configuration Profiles: implementing-config-profiles.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - pymdownx.highlight:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en
