site_name: Configuration Profiles
site_description: This extension provides a data structure for configuration that is organized in configurable profiles
site_author: SYSTOPIA GmbH
repo_url: https://github.com/systopia/config-profiles

theme:
  name: material

nav:
  - Introduction: index.md
  - Implementing Configuration Profiles: implementing-config-profiles.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en
