-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_config_profile`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_config_profile
-- *
-- * Configuration profiles implemented by config type providers.
-- *
-- *******************************************************/
CREATE TABLE `civicrm_config_profile` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique ConfigProfile ID.',
  `type` varchar(255) NOT NULL COMMENT 'Type of configuration profile.',
  `name` varchar(255) NOT NULL COMMENT 'Name of configuration profile.',
  `data` text COMMENT 'Actual profile data as defined by the config profile type provider.',
  `is_active` tinyint NOT NULL DEFAULT 1 COMMENT 'Whether this configuration profile is active.',
  `is_default` tinyint NOT NULL DEFAULT 0 COMMENT 'Whether this is the default configuration profile for this type.',
  `created_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'When the configuration profile was created.',
  `modified_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'When the configuration profile was created or last modified.',
  `access_date` timestamp NULL COMMENT 'When the configuration profile was last accessed.',
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB;
